### ISSUE TITLE
Incompatible with Create on 1.20.1

### ISSUE THREAD

**Issue by Poopooracoocoo** [Uraneptus/SnowPig-fabric-1.16#17]
## Log
[latest.log](https://github.com/Uraneptus/SnowPig-fabric/files/13577091/latest.log)

## Crash report
[crash-2023-12-06_17.05.35-client.txt](https://github.com/Uraneptus/SnowPig-fabric/files/13577101/crash-2023-12-06_17.05.35-client.txt)

Minecraft 1.20.1
Fabric Loader 0.15.0
Fabric API 0.91.0
Create 0.5.1-d-build.1161
Snow Pig 3.0.0

**Comment by Killercrab432** [comment]
can confirm i am also getting this error, any fix on the way?

**Comment by Fyoncle** [comment]
+1

**Comment by ArshiaDPG** [comment]
Ok wow how did I miss this for so long.
I just finished a fix for it, I'll post it if the tests I'm doing rn work.

**Comment by ArshiaDPG** [comment]
I've released a new version that should solve the problem, I'm going to close this issue but feel free to open a new one if the same issue repeats, even if it shouldn't now.

**Comment by Fyoncle** [comment]
> I've released a new version that should solve the problem, I'm going to close this issue but feel free to open a new one if the same issue repeats, even if it shouldn't now.

I appreicate that, i was just too sad that you didn't notice this for a whole year :(
