### ISSUE TITLE
Frosty Snig's duration is wrong in the files

### ISSUE THREAD

**Issue by BatJPJonyGod** [Uraneptus/SnowPig-fabric-1.16#20]
So in the files Frosty Snig is 3720.0 seconds long, which is 62 minutes. I noticed it because when the music finish the jukebox stays powered for a long time after the music ends. It's quite annoying for my jukebox music shuffling with a hopper since it takes 1 hour after Frosty Snig to play another song.

**Comment by Uraneptus** [comment]
I need to test this when I'm home. The value in the code should refer to ticks tho, not seconds. At least as far as I know

**Comment by Uraneptus** [comment]
@ArshiaDPG could you fix this? I think the correct value would be 186 (seconds)

**Comment by ArshiaDPG** [comment]
Just released a fix for it.
