### ISSUE TITLE
Mod Incompatibility: Crashes REI

### ISSUE THREAD

**Issue by SalvieMundi** [Uraneptus/SnowPig-fabric-1.16#4]
Hovering over the item that appears to be a frozen drum stick in REI crashes the client. I have attached a photo and crash report, but I'd assume it's something simple, as it appears to just be an array out of bounds problem.

![image](https://user-images.githubusercontent.com/76707320/132624361-bfbc6aa5-99cf-4f05-9bbf-53ecb7381159.png)

[crash-2021-09-09_01.04.30-client.txt](https://github.com/Uraneptus/SnowPig-fabric/files/7133580/crash-2021-09-09_01.04.30-client.txt)

**Comment by Uraneptus** [comment]
So it appears to me that you're using the 1.16.5 version of snowpig
![2d0fcd5db145f51d29f10a8f68756f71](https://user-images.githubusercontent.com/50745606/132942434-d498aa7e-fddb-4aeb-88c4-895f616e3b48.png)

Could you download the 1.17.1 version and check if this crash still occurs?

**Comment by SalvieMundi** [comment]
Haha well... it seems I may have inadvertantly found another (much more minor) issue. :3 I know I am using the latest jar from curseforge. Check your fabric.mod.json file, and yeah. It's labeled version 1.2.0 for 1.17.x, rather than 1.0.0 for 1.17.x as the file naming convention would suggest.

**Comment by Uraneptus** [comment]
Haha ooops 😅
Gonna change that in a sec!

**Comment by SalvieMundi** [comment]
Tis all good. :D I appreciate your help. ^.^

**Comment by Uraneptus** [comment]
No problem!

Also do you think you could send me your mod list that you used when the crash occurred? Because I can't reproduce it currently

**Comment by SalvieMundi** [comment]
It should be near the bottom of the crash report I attached. It's a pretty long list, but farmer's delight is not installed, which probably has something to do with it since that's the item that is crashing REI.

**Comment by Uraneptus** [comment]
I don't think it's farmer's delight cuz I haven't installed it either

**Comment by Uraneptus** [comment]
Which one is this "AutosmeltEnchant" mod?

**Comment by SalvieMundi** [comment]
https://www.curseforge.com/minecraft/mc-mods/auto-smelt-enchantment

**Comment by Uraneptus** [comment]
Thanks, tho could you pls upload your mods folder somewhere and send it in here? Cuz I don't have the time to download everything that's in the crash log

**Comment by SalvieMundi** [comment]
Will do! Sorry, sleeping haha. We are definitely in different time zones! I will upload a little later in the day!

**Comment by Uraneptus** [comment]
Alright, thanks! :D
And yeah we're in different time zones haha

**Comment by SalvieMundi** [comment]
Here's a zip containing the mods I was using. Some are client side only. Sorry this took so long. Ended up having a long series of errands to run the last two days.

https://drive.google.com/file/d/1_rZYTQ1BqMcJKWn4Y_t4sj9TiLgeaeRZ/view?usp=sharing

**Comment by Uraneptus** [comment]
Soo, I finally had time to look into this, sorry for the wait!
The problem is the combination of apple skin and WTHIT lets the game crash when the player hovers over frozen porkchop in the rei screen. I don't think we can do much in the snow pig mod itsself to fix this. You might wanna open an issue on one of the other mods githubs.

**Comment by SalvieMundi** [comment]
Ah ok, thanks for the support! :) You can close this ticket. If I need to, I can always open another, but it sounds like we know where the problem lies.

**Comment by Uraneptus** [comment]
Alright! Glad I could help :D
