### ISSUE TITLE
[Compat request] Tiny Skeletons

### ISSUE THREAD

**Issue by Dejeh** [Uraneptus/SnowPig-fabric-1.16#7]
Snow pigs killed by Baby Strays from [Tiny Skeletons](https://www.curseforge.com/minecraft/mc-mods/tiny-skeletons-fabric) don't drop their music disc

**Comment by Uraneptus** [comment]
This is planned, tho the implementation of a system that loads different loot tables at the same time, depending on which mods are loaded, is quite tricky so this will take some more time!

**Comment by Uraneptus** [comment]
Added

**Comment by Dejeh** [comment]
I saw you also added support for forge. Thanks for your work! :)
